import Head from "next/head";
import { useState } from "react";
import { Menu, X } from "lucide-react";
import Main from "@/components/Main";
import Expenses from "@/components/expenses";
import Trips from "@/components/Trips";
import Approvals from "@/components/Approvals";
import Settings from "@/components/Settings";
import Support from "@/components/Support";

export default function Home() {
  const [selectedPage, setSelectedPage] = useState("home");
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const handleNavigation = (page) => {
    setSelectedPage(page);
    setIsSidebarOpen(false); // Close sidebar on mobile when navigating
  };

  return (
    <>
      <Head>
        <title>Finance Visualiser</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="flex h-screen bg-gray-900 text-white">
        {/* Mobile Sidebar Toggle */}
        <button
          className="absolute top-4 left-4 z-50 md:hidden p-2 bg-gray-800 rounded-md"
          onClick={() => setIsSidebarOpen(!isSidebarOpen)}
        >
          {isSidebarOpen ? <X size={24} /> : <Menu size={24} />}
        </button>

        {/* Sidebar */}
        <aside
          className={`fixed inset-y-0 left-0 bg-black p-5 flex flex-col justify-between transform transition-transform duration-300 w-64 md:relative md:translate-x-0 ${isSidebarOpen ? "translate-x-0" : "-translate-x-full"
            } md:flex`}
        >
          <div>
            <div className="flex items-center gap-3 mb-6">
              <img
                src="https://png.pngtree.com/png-vector/20190710/ourlarge/pngtree-user-vector-avatar-png-image_1541962.jpg"
                alt="User"
                className="w-12 h-12 rounded-full"
              />
              <span className="text-lg font-semibold">Ayush Dangwal</span>
            </div>

            <nav className="space-y-3">
              {[
                { name: "🏠 Home", key: "home" },
                { name: "💰 Expenses", key: "expenses" },
                { name: "✈️ Trips", key: "trips" },
                { name: "✅ Approvals", key: "approvals" },
                { name: "⚙️ Settings", key: "settings" },
                { name: "📞 Support", key: "support" },
              ].map((item) => (
                <button
                  key={item.key}
                  className={`flex w-full items-center gap-3 p-3 rounded-lg transition ${selectedPage === item.key ? "bg-gray-800" : "hover:bg-gray-800"
                    }`}
                  onClick={() => handleNavigation(item.key)}
                >
                  {item.name}
                </button>
              ))}
            </nav>
          </div>

          <div className="flex items-center justify-center space-x-4">
            <img src="favicon.png" alt="" className="w-8 h-8" />
            <div className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-cyan-400 text-xl font-bold">
              FinVisual
            </div>
          </div>
        </aside>

        {/* Content Section */}
        <div className="flex-1 p-5 overflow-y-auto">
          {selectedPage === "home" && <Main />}
          {selectedPage === "expenses" && <Expenses />}
          {selectedPage === "trips" && <Trips />}
          {selectedPage === "approvals" && <Approvals />}
          {selectedPage === "settings" && <Settings />}
          {selectedPage === "support" && <Support />}
        </div>
      </div>
    </>
  );
}
